import { useState } from 'react'
import { Check, X } from 'lucide-react'

const API=import.meta.env.VITE_API_URL||'/api'
async function api(path,options){const response=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.token}`}}),data=await response.json();if(!response.ok)throw Error(data.message);return data}
export default function ClassActionModal({data,close,onSaved}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[role,setRole]=useState('student')
  async function submit(event){event.preventDefault();setBusy(true);setError('');const values=Object.fromEntries(new FormData(event.currentTarget));try{const response=data.type==='invite'?await api(`/classrooms/${data.course.id}/invite`,{method:'POST',body:JSON.stringify({...values,role})}):await api('/classrooms',{method:'POST',body:JSON.stringify(values)});setResult(response);onSaved?.()}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <div className="backdrop" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="modal"><button className="x" onClick={close}><X/></button>{result?<div className="success"><span><Check/></span><h2>{data.type==='invite'?(result.delivery==='sent'?'Invitation sent':'Invitation created'):'Classroom created'}</h2><p>{data.type==='invite'?(result.delivery==='sent'?`A ${result.role} invitation was emailed to ${result.email}.`:`The ${result.role} invitation link is ready for ${result.email}.`):`Classroom code: ${result.classCode}`}</p>{result.warning&&<p className="error">{result.warning}</p>}{result.link&&<label>Invitation link<input value={result.link} readOnly onFocus={event=>event.target.select()}/></label>}<button className="primary" onClick={close}>Done</button></div>:<><small>{data.type==='invite'?'INVITE PERSON':'NEW CLASSROOM'}</small><h2>{data.type==='invite'?`Invite to ${data.course.name}`:'Create a classroom'}</h2><form onSubmit={submit}>{data.type==='invite'?<><p className="field-label">Invite as</p><div className="roles"><button type="button" className={role==='student'?'on':''} onClick={()=>setRole('student')}>Student</button><button type="button" className={role==='teacher'?'on':''} onClick={()=>setRole('teacher')}>Teacher</button></div><label>{role==='student'?'Student':'Teacher'} email<input name="email" type="email" placeholder={`${role}@university.edu`} required/></label><p className="muted">The link is email-bound and can only be accepted by a registered {role} account.</p></>:<><label>Class name<input name="name" placeholder="Advanced Algorithms" required/></label><label>Subject / course code<input name="subject" placeholder="CS 401" required/></label><label>Section<input name="section" placeholder="Section A"/></label><label>Class color<input name="color" type="color" defaultValue="#6556e8"/></label></>}{error&&<p className="error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?'Please wait…':data.type==='invite'?`Send ${role} invitation`:'Create classroom'}</button></form></>}</section></div>}
