import { useCallback, useEffect, useState } from "react";
import { Check, Download, FileText, RotateCcw, X } from "lucide-react";
import "../../styles/feature-pages.css";
const API = import.meta.env.VITE_API_URL || "/api";
async function api(path, options = {}) { const response = await fetch(API + path, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${localStorage.token}` } }); const data = await response.json(); if (!response.ok) throw Error(data.message); return data; }
export default function ReportsWorkspace({ user }) {
  const [rows, setRows] = useState([]), [rooms, setRooms] = useState([]), [corrections, setCorrections] = useState([]), [filters, setFilters] = useState({ classroomId: "", from: "", to: "" }), [message, setMessage] = useState("");
  const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)).toString();
  const load = useCallback(() => Promise.all([api(`/reports/attendance?${query}`), api("/classrooms"), api("/attendance/corrections")]).then(([records, classrooms, correctionRows]) => { setRows(records); setRooms(classrooms); setCorrections(correctionRows); }).catch((error) => setMessage(error.message)), [query]);
  useEffect(() => { load(); }, [load]);
  async function download(format) { const response = await fetch(`${API}/reports/attendance.${format}?${query}`, { headers: { Authorization: `Bearer ${localStorage.token}` } }); if (!response.ok) return setMessage((await response.json()).message); const blob = await response.blob(), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = `classmark-attendance.${format}`; anchor.click(); URL.revokeObjectURL(url); }
  async function requestCorrection(row) { const requestedStatus = row.status === "present" ? "absent" : "present", reason = prompt(`Request a change to ${requestedStatus}. Explain why:`); if (!reason) return; try { setMessage((await api(`/attendance/${row.id}/corrections`, { method: "POST", body: JSON.stringify({ requestedStatus, reason }) })).message); load(); } catch (error) { setMessage(error.message); } }
  async function decide(id, decision) { const note = prompt(`Optional note for ${decision}:`) || ""; await api(`/attendance/corrections/${id}`, { method: "PATCH", body: JSON.stringify({ decision, note }) }); load(); }
  return <div className="feature-page"><div className="title"><div><small>REPORTING</small><h1>Attendance reports</h1><p>Filter, export, and correct finalized attendance records.</p></div><div className="title-actions"><button className="outline" onClick={() => download("csv")}><Download />CSV</button><button className="primary" onClick={() => download("pdf")}><FileText />PDF</button></div></div>
    <div className="panel report-filters"><label>Classroom<select value={filters.classroomId} onChange={(e) => setFilters({ ...filters, classroomId: e.target.value })}><option value="">All classrooms</option>{rooms.map((room) => <option key={room.id} value={room.id}>{room.name}</option>)}</select></label><label>From<input type="date" value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value })} /></label><label>To<input type="date" value={filters.to} onChange={(e) => setFilters({ ...filters, to: e.target.value })} /></label></div>
    {message && <p className="status-message">{message}</p>}
    <section className="panel data-table"><header><span>Date</span><span>Classroom</span><span>Student</span><span>Status</span><span>Verification</span><span /></header>{rows.map((row) => <div key={row.id}><span>{new Date(row.recordedAt).toLocaleString()}</span><span><b>{row.classroomName}</b><small>{row.subject}</small></span><span><b>{row.studentName}</b><small>{row.identifier}</small></span><span className={`result ${row.status}`}>{row.status}</span><span>{row.method || "—"}</span><span><button className="outline compact" onClick={() => requestCorrection(row)}><RotateCcw />Correct</button></span></div>)}</section>
    <section className="panel corrections"><h2>Correction workflow</h2>{corrections.length ? corrections.map((item) => <article key={item.id}><div><b>{item.studentName || item.classroomName}</b><small>{item.classroomName} · {item.currentStatus} → {item.requested_status}</small><p>{item.reason}</p></div><em className={item.status}>{item.status}</em>{user.role === "teacher" && item.status === "pending" && <><button className="outline" onClick={() => decide(item.id, "rejected")}><X />Reject</button><button className="primary" onClick={() => decide(item.id, "approved")}><Check />Approve</button></>}</article>) : <p className="muted">No correction requests.</p>}</section>
  </div>;
}
